[package]
name = "cch23-bechma"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.2"
axum-extra = { version = "0.9.0", features = ["cookie"] }

shuttle-axum = { version = "0.35.0", default-features = false, features = ["axum-0-7"] }
shuttle-runtime = "0.35.0"

tokio = "1"
tracing = "0.1.40"
serde = "1.0"
serde_json = "1.0"
base64 = "*"

rustemon = "*"

[dev-dependencies]
axum-test = "*"